apiVersion: v1
name: jenkins
description: The leading open source automation server
version: 1.4.1
appVersion: 2.176.2
home: https://jenkins.io/
icon: https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png
sources:
  - https://github.com/codecentric/helm-charts
  - https://github.com/jenkinsci/jenkins
  - https://github.com/jenkinsci/docker
  - https://github.com/jenkinsci/docker-jnlp-slave
keywords:
  - ci
  - continuous integration
  - continuous delivery
  - continuous deployment
  - devops
  - automation
maintainers:
  - name: unguiculus
    email: unguiculus@gmail.com
