{{- $highAvailability := gt (int .Values.keycloak.replicas) 1 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "keycloak.fullname" . }}-startup
  labels:
    app: {{ template "keycloak.name" . }}
    chart: {{ template "keycloak.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  keycloak.cli: |
    embed-server {{- if $highAvailability }} --server-config=standalone-ha.xml{{ end }} --std-out=echo
    batch

  {{- if ne .Values.keycloak.basepath "auth" }}
    # Changes the base path to be /keycloak.basepath instead of /auth
    /subsystem=keycloak-server:write-attribute(name=web-context,value={{ if eq .Values.keycloak.basepath "" }}ROOT{{ else }}{{ .Values.keycloak.basepath }}{{ end }})
    {{- if eq .Values.keycloak.basepath "" }}
    /subsystem=undertow/server=default-server/host=default-host:write-attribute(name=default-web-module,value=keycloak-server.war)
    {{- end }}
  {{ end }}

  {{- with .Values.keycloak.cli }}

    {{- tpl .nodeIdentifier $ | nindent 4 }}

    {{- tpl .logging $ | nindent 4 }}

    {{- tpl .reverseProxy $ | nindent 4 }}

    {{- tpl .datasource $ | nindent 4 }}

    {{- if $highAvailability }}
      {{- tpl .ha $ | nindent 4 }}
    {{- end }}

    {{- with .custom }}
      {{- tpl . $ | nindent 4 }}
    {{- end }}

  {{- end }}

    run-batch
    stop-embedded-server

{{ if .Values.keycloak.sidecar.realms.enabled }}
  realm-importer.sh: |
    {{- tpl .Values.keycloak.realmImporter $ | nindent 4 }}
{{- end }}

{{- with .Values.keycloak.startupScripts }}
{{ toYaml . | nindent 2 }}
{{- end }}
