apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jenkins.fullname" . }}
  labels:
    {{- include "jenkins.masterLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "jenkins.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "jenkins.masterLabels" . | nindent 8 }}
      annotations:
        {{- include "jenkins.configChecksumAnnotations" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      initContainers:
        - name: jenkins-init
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /init/init.sh
          args:
            - "{{ .Values.image.repository }}"
            - "{{ .Values.image.tag }}"
            - "{{ .Values.forcePluginUpdates }}"
          volumeMounts:
            - name: init
              mountPath: /init
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-plugins
              mountPath: /usr/share/jenkins/ref/plugins
          {{- range .Values.referenceContent }}
              {{- if and .relativeDir (hasPrefix "/" (toString .relativeDir)) }}
                {{ fail ".relativeDir must not start with a '/'" }}
              {{- end }}
            - name: {{ include "jenkins.configmapSuffix" . }}
              mountPath: /var/jenkins_ref/{{ .relativeDir }}
          {{- end }}
        {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- with .Values.extraInitContainers }}
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      containers:
        - name: jenkins-master
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: agent
              containerPort: 50000
              protocol: TCP
          env:
            - name: JENKINS_SLAVE_AGENT_PORT
              value: "{{ .Values.service.agent.port }}"
          {{- with .Values.javaOpts }}
            - name: JAVA_OPTS
              value: "{{ . }}"
          {{- end }}
          {{- if .Values.casc.secrets }}
            - name: SECRETS
              value: /casc-secrets
          {{- end }}
          {{- with .Values.extraEnv }}
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          livenessProbe:
          {{- with .Values.livenessProbe }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
          {{- with .Values.readinessProbe }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-plugins
              mountPath: /usr/share/jenkins/ref/plugins
          {{- if .Values.casc.secrets }}
            - name: casc-secrets
              mountPath: /casc-secrets
              readOnly: true
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
            {{- tpl . $ | nindent 12 }}
          {{- end }}
        {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
    {{- end }}
      serviceAccountName: {{ include "jenkins.serviceAccountName" . }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
        - name: jenkins-home
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "jenkins.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: jenkins-plugins
          emptyDir: {}
      {{- if .Values.casc.secrets }}
        - name: casc-secrets
          secret:
            secretName: {{ include "jenkins.cascSecret" . }}
      {{- end }}
        - name: init
          configMap:
            name: {{ include "jenkins.fullname" . }}-init
            defaultMode: 0555
      {{- range .Values.referenceContent }}
        - name: {{ include "jenkins.configmapSuffix" . }}
          configMap:
            name: {{ include "jenkins.fullname" $ }}-{{ include "jenkins.configmapSuffix" . }}
          {{- with .defaultMode }}
            defaultMode: {{ . }}
          {{- end }}
      {{- end }}
      {{- with .Values.extraVolumes }}
        {{- tpl . $ | nindent 8 }}
      {{- end }}
