{{- range .Values.k8sCredentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenkins.fullname" $ }}-{{ required "Secret .nameSuffix is required!" .nameSuffix }}
  labels:
    {{- include "jenkins.masterLabels" $ | nindent 4 }}
    jenkins.io/credentials-type: {{ required "Secret .type is required!" .type }}
  annotations:
    jenkins.io/credentials-description: {{ required "Secret .description is required!" .description }}
  {{- range $key, $mappedKey := .keybindings }}
    jenkins.io/credentials-keybinding-{{ $key }}: {{ $mappedKey }}
  {{- end }}
type: Opaque
data:
{{- range $key, $value := required "Secret .data is required!" .data }}
  {{ $key }}: {{ tpl $value $ | b64enc }}
{{- end }}
{{- end }}
